import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-help-manual',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (open) {
      <div class="modal-mask" (click)="closed.emit()">
        <div class="modal-card" (click)="$event.stopPropagation()">
          <div class="modal-header">
            <span class="modal-title">DeepVision Studio — User Guide</span>
            <button class="btn-ghost" (click)="closed.emit()">✕</button>
          </div>
          <div class="modal-body">
            <h4>Mode A · Forward Propagation Visualizer</h4>
            <p>Select a dataset sample or upload an image. The network runs forward propagation automatically on every change.</p>
            <p>Click any layer node in the network graph to inspect its output tensor, feature maps, channel previews, and activation statistics.</p>
            <p>Conv2D layers support editable kernel matrices. Use the layer palette to add/remove/reorder layers.</p>

            <h4>Mode B · Training Workbench</h4>
            <p>Configure training hyperparameters (batch size, epochs, learning rate, optimizer, scheduler) and select a preset task.</p>
            <p>Click <strong>▶ Start</strong> to begin mock training. Loss and accuracy curves update in real time.</p>
            <p><strong>Note:</strong> Training is currently simulated on the frontend (MOCK mode). Real training will be powered by a Spring Boot backend via REST API + WebSocket in a future version.</p>

            <h4>Architecture Notes</h4>
            <p>Forward pass computation (Conv2D, Pool2D, Dense, Activation, Flatten) is performed with real math in the browser via <code>SimEngine</code>.</p>
            <p>Training metrics are generated by <code>TrainingRuntimeService</code> which provides a clean interface for future backend integration.</p>
          </div>
        </div>
      </div>
    }
  `,
  styles: [`
    .modal-mask { position:fixed;inset:0;background:rgba(15,23,42,.35);display:grid;place-items:center;z-index:1400; }
    .modal-card { width:min(700px,calc(100vw - 24px));background:#ffffff;border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 24px 64px rgba(15,23,42,.18);overflow:hidden; }
    .modal-header { display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid #e2e8f0; }
    .modal-title { font-size:15px;font-weight:700;color:#1f2937; }
    .modal-body { padding:18px;color:#64748b;line-height:1.65;max-height:70vh;overflow-y:auto; }
    .modal-body p { margin:0 0 10px; }
    .modal-body h4 { color:#2563eb;font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin:16px 0 6px; }
    .modal-body code { background:#f1f5f9;padding:1px 5px;border-radius:4px;font-size:11px;color:#1d4ed8; }
    .modal-body strong { color:#1f2937; }
    .btn-ghost { background:transparent;border:1px solid transparent;color:#64748b;cursor:pointer;padding:4px 8px;border-radius:6px;font-size:14px; }
    .btn-ghost:hover { color:#1f2937;border-color:#cbd5e1;background:#f8fafc; }
  `]
})
export class HelpManualComponent {
  @Input() open = false;
  @Output() closed = new EventEmitter<void>();
}
