package com.deepvision.studio.forward;

import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.Instant;

public final class ForwardRecordDtos {
  private ForwardRecordDtos() {}

  @Schema(description = "Request body for saving a Mode A forward-pass snapshot")
  public record SaveForwardRecordRequest(
      @Schema(description = "User-visible record name", example = "Edge kernel experiment")
      @NotBlank(message = "Record name is required.")
      @Size(max = 120, message = "Record name must be at most 120 characters.")
      String name,
      @Schema(description = "Selected network template id", example = "cnn-classic")
      @NotBlank(message = "Template id is required.")
      String templateId,
      @Schema(description = "Dataset or sample collection name", example = "Animal")
      @NotBlank(message = "Dataset name is required.")
      String datasetName,
      @Schema(description = "Number of layers in the saved graph", example = "6")
      int layerCount,
      @Schema(description = "Parameter count shown by the frontend", example = "18432")
      long parameterCount,
      @Schema(description = "Optional preview image Data URL generated by the frontend")
      String previewImageDataUrl,
      @Schema(description = "Full frontend snapshot used to restore Mode A state")
      @NotNull(message = "Snapshot is required.")
      JsonNode snapshot
  ) {}

  @Schema(description = "Summary item for a saved Mode A record")
  public record ForwardRecordSummary(
      Long id,
      String name,
      String templateId,
      String datasetName,
      int layerCount,
      long parameterCount,
      String imagePath,
      Instant createdAt
  ) {
    static ForwardRecordSummary from(ForwardRecord record) {
      return new ForwardRecordSummary(
          record.getId(),
          record.getName(),
          record.getTemplateId(),
          record.getDatasetName(),
          record.getLayerCount(),
          record.getParameterCount(),
          record.getImagePath(),
          record.getCreatedAt()
      );
    }
  }

  @Schema(description = "Detail payload for a saved Mode A record")
  public record ForwardRecordDetail(
      Long id,
      String name,
      String templateId,
      String datasetName,
      int layerCount,
      long parameterCount,
      String imagePath,
      Instant createdAt,
      JsonNode snapshot
  ) {
    static ForwardRecordDetail from(ForwardRecord record, JsonNode snapshot) {
      return new ForwardRecordDetail(
          record.getId(),
          record.getName(),
          record.getTemplateId(),
          record.getDatasetName(),
          record.getLayerCount(),
          record.getParameterCount(),
          record.getImagePath(),
          record.getCreatedAt(),
          snapshot
      );
    }
  }
}
